name: Publish Plugin

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get package version
        id: package-version
        run: echo "version=$(grep '^version =' Cargo.toml | sed -e 's/.*= \"v*//' -e 's/\"//')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/protobuf2zod:v${{ steps.package-version.outputs.version }}
          platforms: linux/amd64

      - name: Set up Buf
        uses: bufbuild/setup-buf@v1

      - name: Log in to Buf Schema Registry
        run: buf registry login --username ${{ secrets.BUF_USERNAME }} --token-stdin <<< "${{ secrets.BUF_TOKEN }}"

      - name: Push plugin to BSR
        run: |
          buf beta registry plugin push \
            --visibility public \
            --image ghcr.io/${{ github.repository_owner }}/protobuf2zod:v${{ steps.package-version.outputs.version }}
